/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychainsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author imanalnahwi
 */
public class MainMenuFrame extends javax.swing.JFrame {

    // The person who logged in (Manager or Staff)
    private Person loggedInUser;

    /**
     * Creates new form MainMenuFrame — used by NetBeans GUI designer.
     */
    public MainMenuFrame() {
        
        initComponents();
        pack();
    }

    /**
     * Used at run time: receives the logged-in user from LoginFrame.
     */
    public MainMenuFrame(Person user) {
        pack();
        this.loggedInUser = user;
        initComponents();
        setupWelcomeLabel();
        loadStatCounts();
        loadUsersTable();
        btnSuppliers.addActionListener(e -> btnSuppliersClicked());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblUserInfo = new javax.swing.JLabel();
        pnlLeft = new javax.swing.JPanel();
        btnSuppliers = new javax.swing.JButton();
        btnProducts = new javax.swing.JButton();
        btnOrders = new javax.swing.JButton();
        btnQuery = new javax.swing.JButton();
        btxLogout = new javax.swing.JButton();
        pnlStats = new javax.swing.JPanel();
        pnnCardSuppliers = new javax.swing.JPanel();
        lblCountSuppliers = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlCardProducts = new javax.swing.JPanel();
        lblCountProducts = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlCardOrders = new javax.swing.JPanel();
        lblCountOrders = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 32, 960, 680));
        setPreferredSize(new java.awt.Dimension(900, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTop.setBackground(new java.awt.Color(110, 106, 200));
        pnlTop.setPreferredSize(new java.awt.Dimension(900, 60));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Supply Chain System");
        lblTitle.setBounds(new java.awt.Rectangle(20, 15, 300, 30));

        lblWelcome.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcom, Admin");
        lblWelcome.setBounds(new java.awt.Rectangle(620, 20, 250, 25));

        lblUserInfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUserInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblUserInfo.setText("user Info");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 780, 79));

        pnlLeft.setBackground(new java.awt.Color(80, 76, 160));
        pnlLeft.setPreferredSize(new java.awt.Dimension(160, 0));
        pnlLeft.setLayout(new java.awt.GridLayout(5, 0, 0, 5));

        btnSuppliers.setBackground(new java.awt.Color(110, 106, 200));
        btnSuppliers.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnSuppliers.setForeground(new java.awt.Color(255, 255, 255));
        btnSuppliers.setText("🏢 Suppliers");
        btnSuppliers.setBorderPainted(false);
        btnSuppliers.setFocusPainted(false);
        pnlLeft.add(btnSuppliers);

        btnProducts.setBackground(new java.awt.Color(110, 106, 200));
        btnProducts.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnProducts.setText("📦 Products");
        btnProducts.setBorderPainted(false);
        btnProducts.setFocusPainted(false);
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        pnlLeft.add(btnProducts);

        btnOrders.setBackground(new java.awt.Color(110, 106, 200));
        btnOrders.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnOrders.setText("📋 Orders");
        btnOrders.setBorderPainted(false);
        btnOrders.setFocusPainted(false);
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });
        pnlLeft.add(btnOrders);

        btnQuery.setBackground(new java.awt.Color(110, 106, 200));
        btnQuery.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnQuery.setForeground(new java.awt.Color(255, 255, 255));
        btnQuery.setText("🔍 Query");
        btnQuery.setBorderPainted(false);
        btnQuery.setFocusPainted(false);
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });
        pnlLeft.add(btnQuery);

        btxLogout.setBackground(new java.awt.Color(192, 57, 43));
        btxLogout.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btxLogout.setForeground(new java.awt.Color(255, 255, 255));
        btxLogout.setText("🚪 Logout");
        btxLogout.setBorderPainted(false);
        btxLogout.setFocusPainted(false);
        btxLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxLogoutActionPerformed(evt);
            }
        });
        pnlLeft.add(btxLogout);

        getContentPane().add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 770));

        pnlStats.setBackground(new java.awt.Color(240, 240, 245));
        pnlStats.setPreferredSize(new java.awt.Dimension(0, 80));
        pnlStats.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        pnnCardSuppliers.setBackground(new java.awt.Color(255, 255, 255));
        pnnCardSuppliers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 220), 2));
        pnnCardSuppliers.setPreferredSize(new java.awt.Dimension(150, 40));

        lblCountSuppliers.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        lblCountSuppliers.setForeground(new java.awt.Color(110, 106, 200));
        lblCountSuppliers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountSuppliers.setText("0");
        lblCountSuppliers.setPreferredSize(new java.awt.Dimension(100, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 100, 100));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Suppliers :");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 220), 2));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 50));

        javax.swing.GroupLayout pnnCardSuppliersLayout = new javax.swing.GroupLayout(pnnCardSuppliers);
        pnnCardSuppliers.setLayout(pnnCardSuppliersLayout);
        pnnCardSuppliersLayout.setHorizontalGroup(
            pnnCardSuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnnCardSuppliersLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnnCardSuppliersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCountSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        pnnCardSuppliersLayout.setVerticalGroup(
            pnnCardSuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnnCardSuppliersLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnlStats.add(pnnCardSuppliers);

        pnlCardProducts.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardProducts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 220), 2));
        pnlCardProducts.setPreferredSize(new java.awt.Dimension(150, 40));

        lblCountProducts.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        lblCountProducts.setForeground(new java.awt.Color(110, 106, 200));
        lblCountProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountProducts.setText("0");
        lblCountProducts.setPreferredSize(new java.awt.Dimension(100, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(100, 100, 100));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Products :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 220), 2));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 50));

        javax.swing.GroupLayout pnlCardProductsLayout = new javax.swing.GroupLayout(pnlCardProducts);
        pnlCardProducts.setLayout(pnlCardProductsLayout);
        pnlCardProductsLayout.setHorizontalGroup(
            pnlCardProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardProductsLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(pnlCardProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardProductsLayout.createSequentialGroup()
                        .addComponent(lblCountProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardProductsLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        pnlCardProductsLayout.setVerticalGroup(
            pnlCardProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardProductsLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pnlStats.add(pnlCardProducts);

        pnlCardOrders.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardOrders.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 220), 2));
        pnlCardOrders.setPreferredSize(new java.awt.Dimension(150, 40));

        lblCountOrders.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        lblCountOrders.setForeground(new java.awt.Color(110, 106, 200));
        lblCountOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountOrders.setText("0");
        lblCountOrders.setPreferredSize(new java.awt.Dimension(100, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(100, 100, 100));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Orders :");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 220), 2));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 50));

        javax.swing.GroupLayout pnlCardOrdersLayout = new javax.swing.GroupLayout(pnlCardOrders);
        pnlCardOrders.setLayout(pnlCardOrdersLayout);
        pnlCardOrdersLayout.setHorizontalGroup(
            pnlCardOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardOrdersLayout.createSequentialGroup()
                .addGroup(pnlCardOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCardOrdersLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCardOrdersLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblCountOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnlCardOrdersLayout.setVerticalGroup(
            pnlCardOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardOrdersLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pnlStats.add(pnlCardOrders);

        getContentPane().add(pnlStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 780, 220));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBounds(new java.awt.Rectangle(0, 0, 750, 480));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTable1.setForeground(new java.awt.Color(50, 50, 50));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(220, 220, 235));
        jTable1.setRowHeight(35);
        jTable1.setSelectionBackground(new java.awt.Color(110, 106, 200));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setSize(new java.awt.Dimension(754, 580));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 106, 200));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText(" 👥  System Users ");
        jLabel3.setBounds(new java.awt.Rectangle(15, 10, 300, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 287, 780, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        if (loggedInUser instanceof Staff) {
            Staff s = (Staff) loggedInUser;
            if (!s.canAccessProducts()) {
                JOptionPane.showMessageDialog(this,
                    "Access Denied\nYour account does not have permission to access Products.\n",
                    "Unauthorized Access", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        new ProductFrame().setVisible(true);
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
        if (loggedInUser instanceof Staff) {
            Staff s = (Staff) loggedInUser;
            if (!s.canAccessOrders()) {
                JOptionPane.showMessageDialog(this,
                    "Access Denied\nYour account does not have permission to access Orders.\n",
                    "Unauthorized Access", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        new OrderFrame().setVisible(true);
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void btxLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxLogoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Logout", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new LoginFrame().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btxLogoutActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        // TODO add your handling code here:
        if (loggedInUser instanceof Manager) {
            new QueryFrame().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                "Access Denied\nOnly managers can access the Query screen.",
                "Unauthorized Access",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnQueryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuFrame().setVisible(true);
            }
        });
    }

    
    private void btnSuppliersClicked() {
        if (loggedInUser instanceof Staff) {
            Staff s = (Staff) loggedInUser;
            if (!s.canAccessSuppliers()) {
                JOptionPane.showMessageDialog(this,
                    "Access Denied\nYour account does not have permission to access Suppliers.\n",
                    "Unauthorized Access", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        new SupplierFrame().setVisible(true);
    }

   
    private void setupWelcomeLabel() {
        String username;
        String password;
        String role;
        if (loggedInUser instanceof Manager) {
            Manager m = (Manager) loggedInUser;
            username = m.getUsername();
            password = m.getPassword();
            role = "Manager";
        } else {
            Staff s = (Staff) loggedInUser;
            username = s.getUsername();
            password = s.getPassword();
            role = s.getDepartment();
        }
        
        lblWelcome.setText("Welcome,  " + loggedInUser.getName() + "   |   " + role);
        
        lblUserInfo.setText("User: " + username + "    Pass: " + password);
    }

    
    private void loadStatCounts() {
        try {
            lblCountSuppliers.setText(
                String.valueOf(new SupplierDB().getAllSuppliers().size()));
            lblCountProducts.setText(
                String.valueOf(new ProductDAO().getAllProducts().size()));
            lblCountOrders.setText(
                String.valueOf(new OrderDB().getAllOrders().size()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

   
    private void loadUsersTable() {
        String allDepts = String.join(", ", Staff.DEPARTMENTS);
        DefaultTableModel model =
            new DefaultTableModel(
                new String[]{"Name", "Role", "Department"}, 0) {
            public boolean isCellEditable(int r, int c) { return false; }
        };
        try {
            Connection conn = DatabaseConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(
                "SELECT name, role, department FROM users ORDER BY role DESC, name ASC");
            java.sql.ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String dept = rs.getString("department");
                String display = (dept == null || dept.isEmpty()) ? allDepts : dept;
                model.addRow(new Object[]{
                    rs.getString("name"),
                    rs.getString("role"),
                    display
                });
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }
        jTable1.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnQuery;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JButton btxLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCountOrders;
    private javax.swing.JLabel lblCountProducts;
    private javax.swing.JLabel lblCountSuppliers;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserInfo;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlCardOrders;
    private javax.swing.JPanel pnlCardProducts;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlStats;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnnCardSuppliers;
    // End of variables declaration//GEN-END:variables
}
