/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychainsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author imanalnahwi
 */
public class OrderFrame extends javax.swing.JFrame {

    private OrderDB      orderDB    = new OrderDB();
    private OrderItemDB  itemDB     = new OrderItemDB();
    private ProductDAO    productDB  = new ProductDAO();
    private SupplierDB   supplierDB = new SupplierDB();

    private ArrayList<Supplier> supplierList;   
    private ArrayList<Product>  productList;    
    private int selectedOrderId = -1;          
    private int selectedSupplierId = -1;        

    /**
     * Creates new form OrderFrame
     */
    public OrderFrame() {
        initComponents();
        loadSuppliers();
        loadProducts();
        loadOrders();

        
        btnBack.addActionListener(e -> dispose());
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent e) { calcSubtotal(); }
        });
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) { orderSelected(); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        pnlMaster = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        btnNewOrder = new javax.swing.JButton();
        btnUpdateStatus = new javax.swing.JButton();
        btnDeleteOrder = new javax.swing.JButton();
        scrollOrders = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        pnlDetails = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbmProduct = new javax.swing.JComboBox<>();
        txtQty = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        scrollItem = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(770, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTop.setBackground(new java.awt.Color(110, 106, 200));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Order Management");
        lblTitle.setBounds(new java.awt.Rectangle(20, 15, 360, 30));

        btnBack.setBackground(new java.awt.Color(110, 106, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("← Back");
        btnBack.setBorderPainted(false);
        btnBack.setBounds(new java.awt.Rectangle(880, 15, 90, 32));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        pnlMaster.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 106, 200));
        jLabel1.setText("Orders");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 80, 80));
        jLabel2.setText("Supplier :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(80, 80, 80));
        jLabel3.setText("Status :");

        cmbSupplier.setBackground(new java.awt.Color(255, 255, 255));
        cmbSupplier.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSupplierActionPerformed(evt);
            }
        });

        cmbStatus.setBackground(new java.awt.Color(255, 255, 255));
        cmbStatus.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Confirmed", "Delivered" }));

        btnNewOrder.setBackground(new java.awt.Color(39, 174, 96));
        btnNewOrder.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnNewOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnNewOrder.setText("New Order");
        btnNewOrder.setBorderPainted(false);
        btnNewOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewOrder.setFocusPainted(false);
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        btnUpdateStatus.setBackground(new java.awt.Color(230, 126, 43));
        btnUpdateStatus.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnUpdateStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.setBorderPainted(false);
        btnUpdateStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateStatus.setFocusPainted(false);
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        btnDeleteOrder.setBackground(new java.awt.Color(192, 57, 43));
        btnDeleteOrder.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnDeleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteOrder.setText("Delete Order");
        btnDeleteOrder.setBorderPainted(false);
        btnDeleteOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteOrder.setFocusPainted(false);
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderActionPerformed(evt);
            }
        });

        tblOrders.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOrders.setGridColor(new java.awt.Color(220, 200, 235));
        tblOrders.setRowHeight(26);
        tblOrders.setSelectionBackground(new java.awt.Color(110, 106, 200));
        tblOrders.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrollOrders.setViewportView(tblOrders);

        javax.swing.GroupLayout pnlMasterLayout = new javax.swing.GroupLayout(pnlMaster);
        pnlMaster.setLayout(pnlMasterLayout);
        pnlMasterLayout.setHorizontalGroup(
            pnlMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMasterLayout.createSequentialGroup()
                .addGroup(pnlMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMasterLayout.createSequentialGroup()
                        .addComponent(btnNewOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateStatus)
                        .addGap(6, 6, 6))
                    .addGroup(pnlMasterLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMasterLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMasterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
            .addComponent(scrollOrders, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pnlMasterLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbStatus, cmbSupplier});

        pnlMasterLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteOrder, btnNewOrder, btnUpdateStatus});

        pnlMasterLayout.setVerticalGroup(
            pnlMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMasterLayout.createSequentialGroup()
                .addGroup(pnlMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMasterLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(pnlMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewOrder)
                    .addComponent(btnUpdateStatus)
                    .addComponent(btnDeleteOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );

        pnlMasterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3});

        pnlMasterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbStatus, cmbSupplier});

        pnlMasterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDeleteOrder, btnNewOrder, btnUpdateStatus});

        getContentPane().add(pnlMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 770, 250));

        pnlDetails.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 106, 200));
        jLabel4.setText("Order Items");
        jLabel4.setBounds(new java.awt.Rectangle(20, 8, 450, 25));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 80));
        jLabel5.setText("Product :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(80, 80, 80));
        jLabel6.setText("Qty :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(80, 80, 80));
        jLabel7.setText("Unit Price :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(80, 80, 80));
        jLabel8.setText("Subtotal :");

        cbmProduct.setBackground(new java.awt.Color(225, 255, 255));
        cbmProduct.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbmProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbmProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmProductActionPerformed(evt);
            }
        });

        txtQty.setBackground(new java.awt.Color(240, 240, 245));
        txtQty.setForeground(new java.awt.Color(30, 30, 30));

        txtUnitPrice.setBackground(new java.awt.Color(236, 240, 241));
        txtUnitPrice.setForeground(new java.awt.Color(30, 30, 30));
        txtUnitPrice.setEnabled(false);

        txtSubtotal.setBackground(new java.awt.Color(236, 240, 241));
        txtSubtotal.setForeground(new java.awt.Color(30, 30, 30));
        txtSubtotal.setEnabled(false);
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        btnAddItem.setBackground(new java.awt.Color(41, 128, 185));
        btnAddItem.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnAddItem.setForeground(new java.awt.Color(255, 255, 255));
        btnAddItem.setText("Add Item");
        btnAddItem.setBorderPainted(false);
        btnAddItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddItem.setFocusPainted(false);
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnRemoveItem.setBackground(new java.awt.Color(192, 57, 43));
        btnRemoveItem.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnRemoveItem.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveItem.setText("Remove Item");
        btnRemoveItem.setBorderPainted(false);
        btnRemoveItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveItem.setFocusPainted(false);
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(110, 106, 200));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Order Total : $0.00");
        jLabel9.setBounds(new java.awt.Rectangle(680, 283, 300, 30));

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(211, 211, 211))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDetailsLayout.createSequentialGroup()
                                .addComponent(cbmProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDetailsLayout.createSequentialGroup()
                                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemoveItem)))))
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlDetailsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel7, jLabel8});

        pnlDetailsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtQty, txtUnitPrice});

        pnlDetailsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddItem, btnRemoveItem});

        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(cbmProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnRemoveItem))
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlDetailsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, jLabel6, jLabel7, jLabel8});

        pnlDetailsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbmProduct, txtQty, txtSubtotal, txtUnitPrice});

        pnlDetailsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddItem, btnRemoveItem});

        getContentPane().add(pnlDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 302, 770, 170));

        tblItem.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItem.setRowHeight(26);
        tblItem.setSelectionBackground(new java.awt.Color(110, 106, 200));
        tblItem.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrollItem.setViewportView(tblItem);

        getContentPane().add(scrollItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 468, 770, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSupplierActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        int row = tblOrders.getSelectedRow();
        if (row == -1 || selectedOrderId == -1) {
            JOptionPane.showMessageDialog(this, "Please select an order first.");
            return;
        }
        String oldStatus = tblOrders.getValueAt(row, 3).toString();
        String newStatus = (String) cmbStatus.getSelectedItem();

        if (orderDB.updateOrderStatus(selectedOrderId, newStatus)) {
            // When the order becomes Delivered, the goods have arrived add them to stock
            if (!oldStatus.equals("Delivered") && newStatus.equals("Delivered")) {
                for (OrderItem it : itemDB.getItemsByOrderId(selectedOrderId)) {
                    for (Product pr : productDB.getAllProducts()) {
                        if (pr.getProductId() == it.getProductId()) {
                            productDB.updateStock(pr.getProductId(),
                                pr.getStockQuantity() + it.getQuantity());   // goods received
                            break;
                        }
                    }
                }
                loadProductsForSupplier(selectedSupplierId);
            }
            JOptionPane.showMessageDialog(this, "Status updated to: " + newStatus);
            loadOrders();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update status.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        int idx = cmbSupplier.getSelectedIndex();
        if (idx == -1) {
            JOptionPane.showMessageDialog(this, "Please add a supplier first.");
            return;
        }
        Supplier sup = supplierList.get(idx);
        Order o = new Order(0, sup.getId(), new Date(), "Pending", 0.0);
        int newId = orderDB.addOrder(o);
        if (newId > 0) {
            JOptionPane.showMessageDialog(this,
                "Order #" + newId + " created.\nSelect it in the table, then add items below.");
            loadOrders();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to create order.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderActionPerformed
        int row = tblOrders.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select an order first.");
            return;
        }
        int id  = (int) tblOrders.getValueAt(row, 0);
        String status = tblOrders.getValueAt(row, 3).toString();

        // Business rule: a Delivered order can't be deleted (goods already received)
        if (status.equals("Delivered")) {
            JOptionPane.showMessageDialog(this,
                "Cannot delete a Delivered order.\nThe goods have already been received.",
                "Delete Blocked", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Delete order #" + id + " and all its items?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        if (orderDB.deleteOrder(id)) {
            selectedOrderId = -1;
            loadOrders();
            loadProducts();
            tblItem.setModel(new DefaultTableModel(
                new String[]{"ID", "Product", "Qty", "Unit Price", "Subtotal"}, 0));
            jLabel9.setText("Order Total : $0.00");
            JOptionPane.showMessageDialog(this, "Order deleted.");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete order.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteOrderActionPerformed

    private void cbmProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmProductActionPerformed
        int idx = cbmProduct.getSelectedIndex();
        if (idx >= 0 && productList != null && idx < productList.size()) {
            Product p = productList.get(idx);
            txtUnitPrice.setText(String.valueOf(p.getUnitPrice()));
            calcSubtotal();
        }
    }//GEN-LAST:event_cbmProductActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        if (selectedOrderId == -1) {
            JOptionPane.showMessageDialog(this, "Create or select an order first.");
            return;
        }
        int idx = cbmProduct.getSelectedIndex();
        if (idx == -1) {
            JOptionPane.showMessageDialog(this, "No products available. Add products first.");
            return;
        }
        Product p = productList.get(idx);

        int qty;
        try {
            qty = Integer.parseInt(txtQty.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantity must be a whole number.",
                "Invalid Quantity", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (qty <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.");
            return;
        }
        if (qty > 1000) {
            JOptionPane.showMessageDialog(this,
                "Quantity is too large.\nYou can order at most 1000 units in one item.",
                "Quantity Too High", JOptionPane.WARNING_MESSAGE);
            return;
        }
        double unitPrice = p.getUnitPrice();
        double subtotal  = qty * unitPrice;
        OrderItem item = new OrderItem(0, selectedOrderId, p.getProductId(), qty, unitPrice, subtotal);

        if (itemDB.addOrderItem(item)) {
            // No stock change here — stock only goes UP when the order is Delivered
            orderDB.updateOrderTotal(selectedOrderId, itemDB.calculateOrderTotal(selectedOrderId));
            loadItems(selectedOrderId);
            loadOrders();
            txtQty.setText("");
            txtSubtotal.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add item.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        if (selectedOrderId == -1) {
            JOptionPane.showMessageDialog(this, "Select an order first.");
            return;
        }
        int row = tblItem.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select an item to remove.");
            return;
        }
        int itemId = (int) tblItem.getValueAt(row, 0);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Remove this item from the order?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        if (itemDB.deleteOrderItem(itemId)) {
            
            orderDB.updateOrderTotal(selectedOrderId, itemDB.calculateOrderTotal(selectedOrderId));
            loadItems(selectedOrderId);
            loadOrders();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to remove item.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveItemActionPerformed

    
    private void loadSuppliers() {
        supplierList = supplierDB.getAllSuppliers();
        cmbSupplier.removeAllItems();
        for (Supplier s : supplierList) {
            cmbSupplier.addItem(s.getName());
        }
    }

   
    private void loadProducts() {
        productList = productDB.getAllProducts();
        cbmProduct.removeAllItems();
        for (Product p : productList) {
            cbmProduct.addItem(p.getName());
        }
    }

    
    private void loadOrders() {
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID", "Supplier", "Date", "Status", "Total Qty", "Total"}, 0);
        for (Order o : orderDB.getAllOrders()) {
            
            int totalQty = 0;
            for (OrderItem it : itemDB.getItemsByOrderId(o.getOrderId())) {
                totalQty += it.getQuantity();
            }
            model.addRow(new Object[]{
                o.getOrderId(), o.getSupplierName(), o.getOrderDate(),
                o.getStatus(), totalQty, String.format("$%.2f", o.getTotalAmount())
            });
        }
        tblOrders.setModel(model);
    }

    
    private void loadItems(int orderId) {
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID", "Product", "Qty", "Unit Price", "Subtotal"}, 0);
        for (OrderItem it : itemDB.getItemsByOrderId(orderId)) {
            model.addRow(new Object[]{
                it.getItemId(), it.getProductName(), it.getQuantity(),
                String.format("$%.2f", it.getUnitPrice()),
                String.format("$%.2f", it.getSubtotal())
            });
        }
        tblItem.setModel(model);
        double total = itemDB.calculateOrderTotal(orderId);
        jLabel9.setText(String.format("Order Total : $%.2f", total));
    }

    
    private void orderSelected() {
        int row = tblOrders.getSelectedRow();
        if (row == -1) return;
        selectedOrderId = (int) tblOrders.getValueAt(row, 0);
        String status = tblOrders.getValueAt(row, 3).toString();
        cmbStatus.setSelectedItem(status);

        
        selectedSupplierId = -1;
        for (Order o : orderDB.getAllOrders()) {
            if (o.getOrderId() == selectedOrderId) {
                selectedSupplierId = o.getSupplierId();
                break;
            }
        }
        loadProductsForSupplier(selectedSupplierId);
        loadItems(selectedOrderId);
    }

  
    private void loadProductsForSupplier(int supplierId) {
        productList = new ArrayList<>();
        cbmProduct.removeAllItems();
        for (Product p : productDB.getAllProducts()) {
            if (p.getSupplierId() == supplierId) {
                productList.add(p);
                cbmProduct.addItem(p.getName());
            }
        }
    }

    
    private void calcSubtotal() {
        try {
            double price = Double.parseDouble(txtUnitPrice.getText().trim());
            int    qty   = Integer.parseInt(txtQty.getText().trim());
            txtSubtotal.setText(String.format("%.2f", price * qty));
        } catch (NumberFormatException e) {
            txtSubtotal.setText("");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JComboBox<String> cbmProduct;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlMaster;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JScrollPane scrollItem;
    private javax.swing.JScrollPane scrollOrders;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblOrders;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
