/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychainsystem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author imanalnahwi
 */
public class ProductFrame extends javax.swing.JFrame {

    private ProductDAO db = new ProductDAO();                          // products table
    private SupplierDB supplierDB = new SupplierDB();                // to fill supplier dropdown
    private ArrayList<Supplier> supplierList = new ArrayList<>();    // same order as the dropdown
    private ArrayList<Product> deletedProducts = new ArrayList<>();  // for the Restore button

    /**
     * Creates new form ProductEntryFrame
     */
    public ProductFrame() {
        initComponents();
        loadCategories();        // fill Category dropdown from the static array
        loadSuppliers();         // fill Supplier dropdown from the database
        loadProducts();          // fill the table with all products
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        pnlForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        cmbSuppliers = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRestore = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        scrollProducts = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        lblTableTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(701, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTop.setBackground(new java.awt.Color(110, 106, 200));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Product Management");
        lblTitle.setBounds(new java.awt.Rectangle(20, 15, 360, 30));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnBack.setForeground(new java.awt.Color(110, 106, 200));
        btnBack.setText("← Back");
        btnBack.setBorderPainted(false);
        btnBack.setBounds(new java.awt.Rectangle(740, 15, 90, 32));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 387, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 50));

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 80));
        jLabel1.setText("Name :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 80, 80));
        jLabel2.setText("Category :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(80, 80, 80));
        jLabel3.setText("Price :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(80, 80, 80));
        jLabel4.setText("Stock :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 80));
        jLabel5.setText("Supplier :");

        txtPrice.setBackground(new java.awt.Color(240, 240, 245));
        txtPrice.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(30, 30, 30));

        txtStock.setBackground(new java.awt.Color(240, 240, 245));
        txtStock.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtStock.setForeground(new java.awt.Color(30, 30, 30));

        cmbCategory.setBackground(new java.awt.Color(255, 255, 255));
        cmbCategory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbSuppliers.setBackground(new java.awt.Color(255, 255, 255));
        cmbSuppliers.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbSuppliers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtName.setBackground(new java.awt.Color(240, 240, 245));
        txtName.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtName.setForeground(new java.awt.Color(30, 30, 30));

        btnAdd.setBackground(new java.awt.Color(39, 174, 96));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(230, 126, 34));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(192, 57, 43));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRestore.setBackground(new java.awt.Color(52, 152, 219));
        btnRestore.setText("Restore");
        btnRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(127, 140, 141));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormLayout.createSequentialGroup()
                                    .addGap(64, 64, 64)
                                    .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pnlFormLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        pnlFormLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbCategory, cmbSuppliers, txtName, txtPrice, txtStock});

        pnlFormLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnClear, btnDelete, btnRestore, btnUpdate});

        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete)
                        .addComponent(btnRestore)
                        .addComponent(btnClear))
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlFormLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        pnlFormLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbCategory, cmbSuppliers, txtName, txtPrice, txtStock});

        pnlFormLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnClear, btnDelete, btnRestore, btnUpdate});

        getContentPane().add(pnlForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 710, 280));

        pnlTable.setBackground(new java.awt.Color(255, 255, 255));

        scrollProducts.setBounds(new java.awt.Rectangle(20, 45, 860, 220));

        tblProducts.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducts.setGridColor(new java.awt.Color(220, 220, 235));
        tblProducts.setRowHeight(28);
        tblProducts.setSelectionBackground(new java.awt.Color(110, 106, 200));
        tblProducts.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        scrollProducts.setViewportView(tblProducts);

        lblTableTitle.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblTableTitle.setForeground(new java.awt.Color(110, 106, 200));
        lblTableTitle.setText("  📋  Products List : ");

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addComponent(lblTableTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 323, 710, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void loadCategories() {
        cmbCategory.removeAllItems();
        for (String c : Product.ALLOWED_CATEGORIES) {
            cmbCategory.addItem(c);
        }
    }

    
    private void loadSuppliers() {
        cmbSuppliers.removeAllItems();
        supplierList = supplierDB.getAllSuppliers();
        for (Supplier s : supplierList) {
            cmbSuppliers.addItem(s.getName());
        }
    }

    
    private void loadProducts() {
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID", "Name", "Category", "Price", "Stock", "Supplier"}, 0);
        ArrayList<Product> list = db.getAllProducts();
        for (Product p : list) {
            model.addRow(new Object[]{
                p.getProductId(), p.getName(), p.getCategory(),
                p.getUnitPrice(), p.getStockQuantity(), p.getSupplierName()
            });
        }
        tblProducts.setModel(model);
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String name = txtName.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a product name.");
            return;
        }

        
        double price;
        try {
            price = Double.parseDouble(txtPrice.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price must be a number (example: 19.99).",
                "Invalid Price", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (price < 0) {
            JOptionPane.showMessageDialog(this, "Price cannot be negative.");
            return;
        }

       
        int stock;
        try {
            stock = Integer.parseInt(txtStock.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Stock must be a whole number (example: 50).",
                "Invalid Stock", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (stock < 0) {
            JOptionPane.showMessageDialog(this, "Stock cannot be negative.");
            return;
        }

       
        int supIndex = cmbSuppliers.getSelectedIndex();
        if (supIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please add a supplier first.");
            return;
        }
        int supplierId = supplierList.get(supIndex).getId();
        String category = cmbCategory.getSelectedItem().toString();

        Product p = new Product(0, name, category, price, stock, supplierId);
        if (db.addProduct(p)) {
            JOptionPane.showMessageDialog(this, "Product added successfully.");
            loadProducts();
            txtName.setText("");
            txtPrice.setText("");
            txtStock.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add product.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblProducts.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product from the table first.");
            return;
        }

        String name = txtName.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a product name.");
            return;
        }

        double price;
        try {
            price = Double.parseDouble(txtPrice.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price must be a number (example: 19.99).",
                "Invalid Price", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (price < 0) {
            JOptionPane.showMessageDialog(this, "Price cannot be negative.");
            return;
        }

        int stock;
        try {
            stock = Integer.parseInt(txtStock.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Stock must be a whole number (example: 50).",
                "Invalid Stock", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (stock < 0) {
            JOptionPane.showMessageDialog(this, "Stock cannot be negative.");
            return;
        }

        int supIndex = cmbSuppliers.getSelectedIndex();
        if (supIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please select a supplier.");
            return;
        }
        int supplierId = supplierList.get(supIndex).getId();
        String category = cmbCategory.getSelectedItem().toString();

        int id = (int) tblProducts.getValueAt(row, 0);
        Product p = new Product(id, name, category, price, stock, supplierId);
        if (db.updateProduct(p)) {
            JOptionPane.showMessageDialog(this, "Product updated successfully.");
            loadProducts();
            txtName.setText("");
            txtPrice.setText("");
            txtStock.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update product.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblProducts.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product from the table first.");
            return;
        }

        int    id   = (int) tblProducts.getValueAt(row, 0);
        String name = tblProducts.getValueAt(row, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete product: " + name + "?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        // Save a copy first so the Restore button can bring it back
        String category     = tblProducts.getValueAt(row, 2).toString();
        double price        = Double.parseDouble(tblProducts.getValueAt(row, 3).toString());
        int    stock        = Integer.parseInt(tblProducts.getValueAt(row, 4).toString());
        String supplierName = (tblProducts.getValueAt(row, 5) == null)
                            ? "" : tblProducts.getValueAt(row, 5).toString();
        int supplierId = 0;
        for (Supplier s : supplierList) {
            if (s.getName().equals(supplierName)) { supplierId = s.getId(); break; }
        }
        Product backup = new Product(id, name, category, price, stock, supplierId);

        if (db.deleteProduct(id)) {
            deletedProducts.add(backup);   // remember it for Restore
            DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
            model.removeRow(row);          // remove the row from the table
            JOptionPane.showMessageDialog(this,
                "Product deleted. Press Restore to bring it back.");
            txtName.setText("");
            txtPrice.setText("");
            txtStock.setText("");
        } else {
            JOptionPane.showMessageDialog(this,
                "Cannot delete this product.\n"
                + "It is used in one or more orders, so it cannot be removed.",
                "Delete Blocked", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreActionPerformed
        if (deletedProducts.isEmpty()) {
            JOptionPane.showMessageDialog(this, "There is nothing to restore.");
            return;
        }
        // Bring back the last deleted product
        Product last = deletedProducts.get(deletedProducts.size() - 1);
        if (db.addProduct(last)) {
            deletedProducts.remove(deletedProducts.size() - 1);
            JOptionPane.showMessageDialog(this, "Restored: " + last.getName());
            loadProducts();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to restore product.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRestoreActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtName.setText("");
        txtPrice.setText("");
        txtStock.setText("");
        if (cmbCategory.getItemCount() > 0)  cmbCategory.setSelectedIndex(0);
        if (cmbSuppliers.getItemCount() > 0) cmbSuppliers.setSelectedIndex(0);
        tblProducts.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();   // close this window and go back to the main menu
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked
        int row = tblProducts.getSelectedRow();
        if (row == -1) return;   // nothing selected
        txtName.setText(tblProducts.getValueAt(row, 1).toString());
        cmbCategory.setSelectedItem(tblProducts.getValueAt(row, 2).toString());
        txtPrice.setText(tblProducts.getValueAt(row, 3).toString());
        txtStock.setText(tblProducts.getValueAt(row, 4).toString());
        if (tblProducts.getValueAt(row, 5) != null) {
            cmbSuppliers.setSelectedItem(tblProducts.getValueAt(row, 5).toString());
        }

        // If the selected product is low on stock (5 or less), warn the user
        int stock = Integer.parseInt(tblProducts.getValueAt(row, 4).toString());
        if (stock <= 5) {
            String productName = tblProducts.getValueAt(row, 1).toString();
            JOptionPane.showMessageDialog(this,
                "Low stock warning\n\n"
                + "Product : " + productName + "\n"
                + "Only " + stock + " unit(s) left in stock.\n"
                + "Please order more from the supplier.",
                "Low Stock", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tblProductsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRestore;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbSuppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JScrollPane scrollProducts;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
