/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplychainsystem;

import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author imanalnahwi
 */
public class QueryFrame extends javax.swing.JFrame {

    private OrderDB    orderDB    = new OrderDB();
    private SupplierDB supplierDB = new SupplierDB();
    private ArrayList<Order> currentResults = new ArrayList<>();   

    /**
     * Creates new form QueryFrame
     */
    public QueryFrame() {
        initComponents();
        loadSupplierList();                     
        showResults(orderDB.getAllOrders());   
        btnBack.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollSuppliers = new javax.swing.JScrollPane();
        lstSuppliers = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDateFrom = new javax.swing.JTextField();
        txtDateTo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        pnlResults = new javax.swing.JPanel();
        lblCount = new javax.swing.JLabel();
        scrollREsults = new javax.swing.JScrollPane();
        tblResults = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnWriteFile = new javax.swing.JButton();
        btnReadFile = new javax.swing.JButton();
        btnSaveBinary = new javax.swing.JButton();
        btnLoadBinary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(746, 428));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTop.setBackground(new java.awt.Color(110, 106, 200));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Query & Search");
        lblTitle.setBounds(new java.awt.Rectangle(20, 15, 300, 30));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(110, 106, 255));
        btnBack.setText("← Back");
        btnBack.setBorderPainted(false);
        btnBack.setBounds(new java.awt.Rectangle(780, 15, 90, 32));
        btnBack.setFocusPainted(false);

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 465, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(35, 35, 35))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 752, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 106, 200));
        jLabel1.setText("Filter Orders");
        jLabel1.setBounds(new java.awt.Rectangle(20, 8, 200, 25));

        scrollSuppliers.setBounds(new java.awt.Rectangle(20, 68, 210, 115));

        lstSuppliers.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lstSuppliers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollSuppliers.setViewportView(lstSuppliers);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(110, 106, 200));
        jLabel2.setText("Filter by Suppliers :");
        jLabel2.setBounds(new java.awt.Rectangle(20, 40, 680, 25));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(110, 106, 200));
        jLabel3.setText("Status :");
        jLabel3.setBounds(new java.awt.Rectangle(290, 45, 70, 25));

        cbStatus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Pending", "Confirmed", "Delivered" }));
        cbStatus.setBounds(new java.awt.Rectangle(370, 43, 170, 28));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 106, 200));
        jLabel4.setText("Date From (yyyy-MM-dd) :\t");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(110, 106, 200));
        jLabel5.setText("Date To :");

        txtDateFrom.setBackground(new java.awt.Color(240, 240, 245));
        txtDateFrom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDateFrom.setBounds(new java.awt.Rectangle(480, 123, 160, 28));

        txtDateTo.setBackground(new java.awt.Color(240, 240, 245));
        txtDateTo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDateTo.setBounds(new java.awt.Rectangle(480, 123, 160, 28));

        btnSearch.setBackground(new java.awt.Color(41, 128, 185));
        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnSearch.setText("🔍 Search");
        btnSearch.setBorderPainted(false);
        btnSearch.setBounds(new java.awt.Rectangle(290, 163, 120, 32));
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(127, 140, 141));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorderPainted(false);
        btnClear.setBounds(new java.awt.Rectangle(425, 163, 100, 32));
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setFocusPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(txtDateTo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDateFrom, txtDateTo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClear, btnSearch});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnSearch))
                .addGap(20, 20, 20))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5, txtDateFrom, txtDateTo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClear, btnSearch});

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 752, 180));

        pnlResults.setBackground(new java.awt.Color(255, 255, 255));

        lblCount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCount.setForeground(new java.awt.Color(110, 106, 200));
        lblCount.setText("Results : 0 orders");

        scrollREsults.setBounds(new java.awt.Rectangle(20, 15, 860, 210));

        tblResults.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tblResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResults.setGridColor(new java.awt.Color(220, 220, 235));
        tblResults.setRowHeight(26);
        tblResults.setSelectionBackground(new java.awt.Color(110, 106, 200));
        tblResults.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrollREsults.setViewportView(tblResults);

        lblTotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(110, 106, 200));
        lblTotal.setText("Total value : $0.00");

        btnWriteFile.setBackground(new java.awt.Color(39, 174, 96));
        btnWriteFile.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnWriteFile.setForeground(new java.awt.Color(255, 255, 255));
        btnWriteFile.setText("📄 Write Report");
        btnWriteFile.setBorderPainted(false);
        btnWriteFile.setBounds(new java.awt.Rectangle(20, 285, 160, 35));
        btnWriteFile.setFocusPainted(false);
        btnWriteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteFileActionPerformed(evt);
            }
        });

        btnReadFile.setBackground(new java.awt.Color(41, 128, 185));
        btnReadFile.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnReadFile.setForeground(new java.awt.Color(255, 255, 255));
        btnReadFile.setText("📂 Read Report");
        btnReadFile.setBorderPainted(false);
        btnReadFile.setFocusPainted(false);
        btnReadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadFileActionPerformed(evt);
            }
        });

        btnSaveBinary.setBackground(new java.awt.Color(230, 126, 34));
        btnSaveBinary.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnSaveBinary.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveBinary.setText("💾 Save Binary");
        btnSaveBinary.setBorderPainted(false);
        btnSaveBinary.setFocusPainted(false);
        btnSaveBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBinaryActionPerformed(evt);
            }
        });

        btnLoadBinary.setBackground(new java.awt.Color(142, 68, 173));
        btnLoadBinary.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnLoadBinary.setForeground(new java.awt.Color(255, 255, 255));
        btnLoadBinary.setText("📂 Load Binary");
        btnLoadBinary.setBorderPainted(false);
        btnLoadBinary.setFocusPainted(false);
        btnLoadBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadBinaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlResultsLayout = new javax.swing.GroupLayout(pnlResults);
        pnlResults.setLayout(pnlResultsLayout);
        pnlResultsLayout.setHorizontalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnWriteFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReadFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoadBinary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(scrollREsults)
                        .addGap(18, 18, 18)))
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCount)
                    .addComponent(lblTotal))
                .addGap(96, 96, 96))
        );

        pnlResultsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCount, lblTotal});

        pnlResultsLayout.setVerticalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblCount)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResultsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollREsults, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveBinary)
                    .addComponent(btnReadFile)
                    .addComponent(btnWriteFile)
                    .addComponent(btnLoadBinary))
                .addGap(0, 185, Short.MAX_VALUE))
        );

        pnlResultsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCount, lblTotal});

        getContentPane().add(pnlResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 213, -1, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String supplier = lstSuppliers.getSelectedValue();      
        String status   = cbStatus.getSelectedItem().toString();
        if (status.equals("All")) status = "";                 
        String dateFrom = txtDateFrom.getText().trim();
        String dateTo   = txtDateTo.getText().trim();

        ArrayList<Order> results = orderDB.searchOrders(supplier, status, dateFrom, dateTo);
        showResults(results);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        lstSuppliers.clearSelection();
        cbStatus.setSelectedIndex(0);     
        txtDateFrom.setText("");
        txtDateTo.setText("");
        showResults(orderDB.getAllOrders());   
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBinaryActionPerformed
        if (currentResults.isEmpty()) {
            JOptionPane.showMessageDialog(this, "There are no results to save. Search first.");
            return;
        }
        JFileChooser chooser = new JFileChooser();
        chooser.setSelectedFile(new java.io.File("orders_backup.dat"));
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().getAbsolutePath();
            FileManager.writeBinaryFile(currentResults, path);    // BINARY file API
            JOptionPane.showMessageDialog(this, "Binary file saved to:\n" + path);
        }
    }//GEN-LAST:event_btnSaveBinaryActionPerformed

    private void btnReadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadFileActionPerformed
        JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().getAbsolutePath();
            String content = FileManager.readTextFile(path);      
            javax.swing.JTextArea area = new javax.swing.JTextArea(content, 15, 40);
            area.setEditable(false);
            JOptionPane.showMessageDialog(this, new javax.swing.JScrollPane(area),
                "File Content", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnReadFileActionPerformed

    private void btnWriteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteFileActionPerformed
        if (currentResults.isEmpty()) {
            JOptionPane.showMessageDialog(this, "There are no results to write. Search first.");
            return;
        }
        JFileChooser chooser = new JFileChooser();
        chooser.setSelectedFile(new java.io.File("orders_report.txt"));
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().getAbsolutePath();
            FileManager.writeTextReport(currentResults, path);    
            JOptionPane.showMessageDialog(this, "Text report saved to:\n" + path);
        }
    }//GEN-LAST:event_btnWriteFileActionPerformed

    private void btnLoadBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadBinaryActionPerformed
        JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().getAbsolutePath();
            ArrayList<Order> loaded = FileManager.readBinaryFile(path);   
            if (loaded == null) {
                JOptionPane.showMessageDialog(this,
                    "This file is not a valid binary file.\n"
                    + "Please pick a .dat file you saved with 'Save Binary'.",
                    "Invalid File", JOptionPane.ERROR_MESSAGE);
                return;
            }
            showResults(loaded);                                          
            JOptionPane.showMessageDialog(this,
                "Loaded " + loaded.size() + " orders from the binary file.");
        }
    }//GEN-LAST:event_btnLoadBinaryActionPerformed

   
    private void loadSupplierList() {
        ArrayList<Supplier> suppliers = supplierDB.getAllSuppliers();
        String[] names = new String[suppliers.size()];
        for (int i = 0; i < suppliers.size(); i++) {
            names[i] = suppliers.get(i).getName();
        }
        lstSuppliers.setListData(names);
    }

    
    private void showResults(ArrayList<Order> orders) {
        currentResults = orders;
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID", "Supplier", "Date", "Status", "Total"}, 0);
        double total = 0;
        for (Order o : orders) {
            model.addRow(new Object[]{
                o.getOrderId(), o.getSupplierName(), o.getOrderDate(),
                o.getStatus(), String.format("$%.2f", o.getTotalAmount())
            });
            total += o.getTotalAmount();
        }
        tblResults.setModel(model);
        lblCount.setText("Results : " + orders.size() + " orders");          
        lblTotal.setText(String.format("Total value : $%.2f", total));       
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLoadBinary;
    private javax.swing.JButton btnReadFile;
    private javax.swing.JButton btnSaveBinary;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnWriteFile;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<String> lstSuppliers;
    private javax.swing.JPanel pnlResults;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JScrollPane scrollREsults;
    private javax.swing.JScrollPane scrollSuppliers;
    private javax.swing.JTable tblResults;
    private javax.swing.JTextField txtDateFrom;
    private javax.swing.JTextField txtDateTo;
    // End of variables declaration//GEN-END:variables
}
